tutorial_environments.rst
Fix missing `.. code-block::` for output of `env | grep _PATH` in environments tutorial.
=> bugfix: `env` output formatting in environments tutorial

conf.py
The default RTD theme now has code formatted with an ugly green background.  This changes it back to something reasonable.
=> Change pygments style to default

tutorial/examples/0.package.py, tutorial/examples/1.package.py, tutorial/examples/2.package.py, tutorial/examples/3.package.py, tutorial/examples/4.package.py, tutorial/examples/5.package.py, tutorial_packaging.rst
Split off of https://github.com/spack/spack/pull/12270 now that the tutorial docs are in a separate repo.
@tgamblin I removed the "automatically" from the phrasing until the maintainers GitHub action actually works.
@alalazo I will have many more updates to the Packaging Tutorial, just wanted to get this out of the way first. I'll let you know when it's ready to update for Ubuntu 18.
=> Document use of the maintainers field

README.md
Once this [PR](https://github.com/spack/spack-tutorial-container/pull/1) is merged, we could add this text referring to the documentation located there.
=> WIP: Refer to exteral repo for container update process

tutorial_environments.rst
One of the `code-block` directives in the environments tutorial was missing a double colon. The associated code block was missing from the HTML documentation.
=> Fix missing code block in environments tutorial

README.md
The release number in the README had not been updated since we did the
relicense to Apache-2.0 OR MIT in v0.12.0. LLNL-CODE-811652 is Spack's
new LLNL release number.
=> README: Update LLNL release number to Apache-2.0/MIT version

tutorial_buildsystems.rst
We're getting build failures from the old build systems section. It's because of changes in the line numbers in `$spack/lib/spack/spack/build_systems/autotools.py`. This fixes that error.
=> fix build failures

outputs/init_spack.sh
This adds `init_spack.sh` script to be used by subsections to get Spack set up before running commands.
=> Add init spack script

tutorial_advanced_packaging.rst
Hi,
I just stumbled on this typo while working on a `libs` property for a package.
Rémi
=> Fix "recursive" argument in "find_libraries" example.

tutorial_configuration.rst
Tested locally to make sure the `:emphasize-lines:` numbers are correct.
Mostly formatting changes, but I also added a section on using `spack external find`. Let me know if we want more detail than that.
For future tutorials, we will need to update the `packages.yaml` format and the list of supported compilers, but those are fine for now since we're using an older release for this tutorial.
One other section I thought about adding was overriding the default `target:` to use `x86_64` instead of the specific microarchitecture that Spack detects. This is a common use case for users on heterogenous clusters. However, this is problematic because we use a mixed compiler for most of this tutorial, which doesn't support specific microarchs anyway. Is it still worth adding an example with GCC …
=> SC20 updates for Configuration Tutorial

outputs/defs.sh, outputs/modules.sh, outputs/packaging.sh, outputs/scripting.sh
Scripts were assuming that `/project` existed, but it only exists when we bindmount it into the container.  This makes the scripts work in-place in our AWS instance, as well.
=> scripts: update tutorial scripts to work outside of a container

tutorial_basics.rst
Fixes:
1.  Remove reference to setup script for amazon tutorial.
2. Fix hash value embedded in the text.
3. Add `spack install zlib%gcc@6.5.0` output to text. It was already run by generator script.
=> update basics section for sc20

tutorial_basics.rst
gcc@8.3.0 was showing up as a mail link so i formatted this to avoid showing up link.
=> format gcc@8.3.0 otherwise it shows up as a mail link

outputs/packaging/configure-build-options.out, tutorial_packaging.rst
This PR adds highlighting of console entries to emphasize the important lines in the output.  
It also expands on the basis of the `stackstart` addition by repeating the optional packages/features from configure help and refining the associated description.
=> Added highlighting and expanded on stackstart

tutorial_basics.rst
Leftover from when I used to use openssl in the basics section.
=> Remove leftover reference to openssl

outputs/dev.sh
There may be other versions of `hwloc` installed from earlier sections. This ensures we uninstall the correct one.
=> dev workflows: more specific hwloc uninstall

tutorial_spack_scripting.rst
This PR:
- moves the explanation for why we are covering `spack find` to the introduction;
- tweaks transitions;
- removes 'platform' in one use to be consistent with a prior PR; and
- removes an extra 'access'.
=> Additional scripting tutorial refinements including fixes

outputs/config/0.compiler_flags.out, outputs/config/0.externals.out, outputs/config/0.prefs.out, outputs/config/1.externals.out, outputs/config/1.prefs.out, outputs/config/2.externals.out, outputs/config/2.prefs.out, outputs/config/3.externals.out, outputs/config/3.prefs.out, outputs/config/4.externals.out, tutorial_configuration.rst
Fixes https://github.com/spack/spack-tutorial/issues/89
* All modifications to `packages` config are now done within an environment. 
* This is expected to address #89 because there is no confusion about the location of `packages.yaml`, deactivating the environment is sufficient to undo the config changes
* Specification of externals was based on `v0.15`. Externals are now (as of `v0.16.1`) specified differently and the tutorial is likewise updated to reflect that.
* The environment scope is now included in the scope prioritization table
Other notes:
* compilers/high-level config tutorial sections are still done outside of an environment
TODOs
=> Configuration tutorial section updates

tutorial_packaging.rst
Highlights:
- Fixed typos;
- Corrected grammar;
- Made explanation of a Spack package it's own section;
- Added more links to Spack documentation;
- Changed `Note`-like sentences and paragraphs to actual notes; and
- Changed bullets from `-` to `*` (since former not showing up on `readthedocs` anymore).
=> Package Creation tutorial updates

tutorial_packaging.rst
This PR corrects highlighting for the newly (and automatically) updated outputs; indents bullets (in the off chance it might help them actually show up); moves some content around the outputs; and tweaks wording.
=> bugfix+updates: Fixed packaging outputs highlighting and tweaked wording

index.rst, outputs/Makefile, outputs/basics.sh, outputs/defs.sh, outputs/env.sh, outputs/environments/add-1.out, outputs/environments/add-2.out, outputs/environments/add-3.out, outputs/environments/add-anonymous-1.out, outputs/environments/anonymous-create-2.out, outputs/environments/concretize-f-1.out, outputs/environments/config-get-1.out, outputs/environments/env-create-2.out, outputs/environments/env-install-1.out, outputs/environments/env-status-2.out, outputs/environments/env-swap-1.out, outputs/environments/env-uninstall-1.out, outputs/environments/find-no-env-1.out, outputs/environments/install-anonymous-1.out, outputs/environments/lockfile-1.out, outputs/environments/show-paths-1.out, outputs/environments/spec-1.out, outputs/environments/spec-2.out, outputs/environments/use-mpi-1.out, outputs/environments/use-trilinos-1.out, outputs/init_spack.sh, tutorial_environments.rst
This isn't done yet -- I still need to run all the commands and change output, but edits would be appreciated on the .rst.
=> environments: move environments tutorial to be *before* configuration

tutorial_packaging.rst
I forgot to fix the spec query examples to indicate they are inclusive.
=> Fix spec queries in package creation section

index.rst
Commit for the version of the tutorial tagged as `ecp21`. Not sure why the video stopped working, but I stripped out some of the html that seemed pointless. Local preview isn't working for me in VS Code, but this markup matches some examples I found of embedded YouTube videos in .rst files.
=> Clean up video html

tutorial_environments.rst
The note pretty much only provides links to the documentation.
The change is a preliminary response to a PEARC tutorial question about environments vs. `spack load` vs. `module load`.
=> Environments: Add a note referencing Spack's module docs

tutorial_buildsystems.rst, tutorial_configuration.rst
=> sc21: update "build systems" and "configuration"

outputs/env.sh, outputs/environments/env-swap-1.out, tutorial_environments.rst
Mostly minor grammar and typo fixes.
I did notice that `trilinos ^mpich` (the default setting during [Reconcretizing the environment](https://spack-tutorial.readthedocs.io/en/latest/tutorial_environments.html#reconcretizing-the-environment)), was not in the buildcache, but later sections assume it is installed. I tried to add it to `outputs/env.sh` but I'm not sure if that's what we use to create the buildcache or not.
@tgamblin @alalazo
=> Environments: minor updates to tutorial

outputs/basics.sh, outputs/basics/clone.out, tutorial_basics.rst
Mostly minor updates to grammar. There was a missing section of output that I added.
Other bugs that I noticed but didn't attempt to fix:
Error during cmake installation.
```console
==> Installing cmake-3.21.4-anj6kcxdxzhfufoypya56mmsmxlyucea
==> Fetching file:///mirror/build_cache/linux-ubuntu18.04-x86_64/gcc-7.5.0/cmake-3.21.4/linux-ubuntu18.04-x86_64-gcc-7.5.0-cmake-3.21.4-anj6kcxdxzhfufoypya56mmsmxlyucea.spack
==> Extracting cmake-3.21.4-anj6kcxdxzhfufoypya56mmsmxlyucea from binary cache
==> Warning: patchelf --print-rpath /home/spack/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/cmake-3.21.4-anj6kcxdxzhfufoypya56mmsmxlyucea/share/cmake-3.21/Modules/Internal/CPack/CPack.OSXScriptLauncher.in produced an error [Command exited with status 1: …
```
=> Basics: minor updates to tutorial

docker/Dockerfile, docker/config.yaml, outputs/Makefile, outputs/defs.sh
To create a docker image to update the output files, from within the `docker` directory:
```console
$ docker build -t spack/tutorial:latest .
```
=> Update S3 buildcache URL, add deprecated:true in config

outputs/module-configs/lmod.1.yaml, outputs/module-configs/lmod.2.yaml, outputs/modules.sh, tutorial_modules.rst
Updates the tutorial for spack/spack#31569.
For a long time the module configuration has had a few settings that use `blacklist`/`whitelist` terminology. We've been asked by some of our users to replace this with more inclusive language. In addition to being non-inclusive, `blacklist` and `whitelist` are inconsistent with the rest of Spack, which uses `include` and `exclude` for the same concepts.
This updates the tutorial to account for this deprecation in Spack.
=> Deprecate `whitelist`/`blacklist` for `include`/`exclude`

docker/Dockerfile
A bit more convenient when dealing with `git` commands etc
=> install bash-completion

docker/init.sh, tutorial_buildsystems.rst, tutorial_configuration.rst, tutorial_modules.rst
In a few parts of the tutorial we were still including literals from Spack v0.17.
Modifications:
=> Update `_spack_root` submodule to v0.19.0

tutorial_developer_workflows.rst
The proposed changes to the documentation will make it clear for the users to use the spack develop command with more clarity.
The second point highlights the need to add the right spec to the spack.yaml environments file by using `spack add <package>` command. This is important because the spack develop command only adds the `dev_path=` attribute to the spec and not the spec itself. I myself missed this and had to struggle a bit until I realised this.
Is this a reasonable suggestion? Would you write it some other way? Or do you think its actually obvious and I only missed it accidentally?
=> Update gotchas in the developer workflow

tutorial_configuration.rst
I found out the hard way that the `target` field only supports architecture families. Unless it's already documented somewhere and I couldn't find it, I'd like to add it.
```
==> Error: the "target" field in compilers.yaml accepts only target families [replace "x86_64_v3" with "x86_64" in "intel@2022.1.0" specification]
```
=> document compiler target field

tutorial_modules.rst
Assuming you're in ~, there's no share folder there.
=> wrong path to setup-env.sh?

outputs/cache.sh, tutorial_binary_cache.rst
- simplify binary cache example
- remove comments about unix permissions
- reword the buildcache create stuff
=> buildcache fixes

outputs/Makefile
Podman needs `--userns=keep-id` because we otherwise end up with files being owned by root in the container, and `--security-opt label=disable` because SELinux blocks access otherwise.
=> Add Podman support

_static/css/custom.css, conf.py
Avoid endless scrolling on the page by setting max height on outputs
=> max height outputs

outputs/Makefile
- New cache (gmake -> zlib-ng should be there)
- Added `jq`
=> Bump container digest

outputs/environments.sh
Apparently it errors when > nproc, like in github actions, so fix to 2 instead
of 4
=> mpirun: 2 ranks

.github/workflows/build.yaml
Building the documentation locally I'm unable to reproduce the error with the dot visualizations that are showing up in the online documentation. Sphinx's documentation mentions that graphviz now outputs to SVG instead of PNG by default so it may be worth reverting to PNG to see if that fixes the diagrams on the site.
=> Modify graphiz to output diagrams as PNGs to emulate previous default

.readthedocs.yaml
Adding `graphviz` as an apt package that is installed into the environment. Should fix issues with graphs not being displayed properly in the docs.
=> Add graphviz to the readthedocs build environment

outputs/environments.sh, outputs/environments/lockfile-1.out
Process spack.lock with `jq` before showing output snippet.
=> make spack.lock more readable by processing first with jq

common/setup.rst, index.rst, outputs/defs.sh
This updates the branch in `defs.sh` to `releases/v0.21`. The tag of the docker image is updated to `sc23`. That tag should be generated automatically whenever the final version of the sc23 tutorial is tagged in this repository.
=> Update branches and tags for SC23

tutorial/examples/Cmake/2.package.py, tutorial_buildsystems.rst, tutorial_configuration.rst, tutorial_modules.rst, tutorial_packaging.rst, tutorial_spack_scripting.rst
Build Systems Tutorial needs a complete overhaul since we overhauled multi-build system support and changed how Python packages are installed. But we aren't giving that tutorial today so this can wait.
=> Update line numbers

tutorial_binary_cache.rst
I was in Markdown mode, and botched the links in the mirrors
=> Replace erroneous markdown links with RST

tutorial_basics.rst
Adds a quick explanation of the `gcc-runtime` and `glibc` nodes on the first install.
=> explain runtimes on first install

.github/workflows/containers.yaml
Because who has time to wait for the nightly job to pick up the new changes.
=> ci: rebuild container on merge to main

outputs/scripting/0.find_exclude.py.example, outputs/scripting/1.find_exclude.py.example, outputs/scripting/2.find_exclude.py.example, outputs/scripting/spack-python-db-query-exclude.out
We'd forgotten to update the tutorial examples when we moved to `spack.store.STORE`. Fixing that here.
=> scripting: add globals for store.STORE

tutorial_binary_cache.rst
Depends on Spack updates in: https://github.com/spack/spack/pull/46549
=> Use environment variable instead of string for OCI token

tutorial_stacks.rst
no content updates needed -- updated EDITOR from `emacs` to `emacs -nw`.
=> update stacks section for sc24

index.rst, outputs/scripting/1.find_exclude.py.example, tutorial_scripting.rst
1. Remove distracting setup section that wastes time
2. Fix typo in find/exclude example
3. Rename .rst file to match the rest of the tutorial
NOTE: Do not merge without checking outputs. The output generation messes with the example text and I want to double-check that it's not the source of the find/exclude typo before merging.
=> update scripting section

tutorial_developer_workflows.rst
Just inline the commands as console blocks rather than generate the output but restore the information.
Could try to fix the output generation if desired.
=> Add back developer extension

tutorial_environments.rst
Within non-interactive shells, e.g., a bash script, aliases are not expanded by default.
This could result in unexpected behavior (spacktivate not recognized as a command).
Add a cautionary note to the environment tutorial regarding this issue, including how to set the expand_aliases shell option for bash.
=> Add note regarding alias behavior for spacktivate

tutorial_basics.rst, tutorial_binary_cache.rst, tutorial_buildsystems.rst
This PR requires and builds off of #431. Manually reviewing and adding suggestions from #430.
=> Fix typos and add suggestions

tutorial_packaging.rst, tutorial_scripting.rst, tutorial_stacks.rst
I corrected various objective spelling and grammatical errors in:
- tutorial_packaging.rst
- tutorial_scripting.rst
- tutorial_stacks.rst
My changes include fixing typos, removing redundant words, and improving sentence structure for clarity while adhering to the constraint of not making subjective style changes or altering reStructuredText formatting (e.g., double backticks).
=> Fix: Correct spelling and grammar in tutorial files

tutorial_advanced_packaging.rst, tutorial_basics.rst, tutorial_binary_cache.rst, tutorial_buildsystems.rst
I corrected various spelling and grammar mistakes in the following files:
- tutorial_advanced_packaging.rst
- tutorial_basics.rst
- tutorial_binary_cache.rst
- tutorial_buildsystems.rst
=> I fixed typos and grammatical errors in your tutorial documentation.

tutorial_advanced_packaging.rst
Fixing a few of the last remaining old style inline code blocks. For reference I used,
```
sed -i  's/:code:`\([^`]*\)`/``\1``/g' tutorial_*.rst
```
=> Update :code:`Something` -> ``Something``

conf.py, index.rst, tutorial_advanced_packaging.rst, tutorial_basics.rst, tutorial_binary_cache.rst, tutorial_buildsystems.rst, tutorial_configuration.rst, tutorial_developer_workflows.rst, tutorial_environments.rst, tutorial_modules.rst, tutorial_packaging.rst, tutorial_scripting.rst, tutorial_stacks.rst
Changing the *rst files for now, the rest of the outdated notices are in package.py files that will be updated soon.
=> Update of license headers

.github/workflows/ci.yml, .github/workflows/style.yml, Makefile, index.rst
=> format index.rst according to new rules

outputs/basics/help-spec.out, tutorial_basics.rst, tutorial_binary_cache.rst
=> add note about spack help --spec

tutorial_basics.rst
This section seems to be fine. The only place that would need updates is the compiler installation at the end. I left the script as it is, but added a tip that starting from Spack v1.0 adding Spack installed compilers to config is not needed anymore.
=> Minor updates to "Basic Installation" section

tutorial_packaging.rst
Link is broken after https://github.com/spack/spack/pull/50884 split the packaging guide into separate sections. Replace with a link to the new first section page of the packaging guide.
=> Fix broken link to old packaging guide page

outputs/basics.sh, tutorial_basics.rst
=> basics: update for Spack 1.0 and other minor improvements

outputs/basics.sh, tutorial_basics.rst
The `spack graph` command demo on hdf5 was designed to be on something simple enough that the ASCII graph was sufficient. That's not true for hdf5 anymore, so we switch to doing it for tcl.
Also add an example using `spack spec` as part of the hdf5 demos.
=> basics: move graph example to tcl (from hdf5) demo `spack spec hdf5`

.github/workflows/ci.yml, outputs/environments.sh, tutorial_environments.rst
- move discussion of incremental builds to later in the section
=> environments: update for pearc25

common/setup.rst
This PR updates the common setup for the HPCIC'25 tutorial *and* adds a warning about the use of `spack tutorial -y`.
=> Setup: update to v1.0, hpcic; add a spack tutorial warning

outputs/config/0.compiler_flags.out, outputs/config/0.prefs.out, outputs/config/1.prefs.out, outputs/config/2.externals.out, outputs/config/3.prefs.out, tutorial_configuration.rst
* Right now ~just the compilers part and intro are updated~ everything up to the "Installation Permissions" section is updated (I don't anticipate any major edits in that section or any after)
* For intro:
* overrides (`::`) use `config:` section as example
* For compilers
* Compilers are in the `packages:` section
* And some attributes have moved around inside of it (but generally look the same)
* can't set `target` in the compiler entry anymore
* Toolchain example is added for hybrid compiler
* Packages: 
* concretization examples updated (they are all different because e.g. compiler modeling)
* preferences for compilers is done differently now (~I use `require:`~ Update August 4: I'm now using `prefer:` and later on using require for `hdf5~mpi`, which is smoother overall)
* …
=> Update config tutorial section to 1.0

index.rst
=> hpcic25: add hpcic25 information to the index.rst

requirements.txt
Fix dependencies allowing us to build the docs with the furo theme.
(Apparently not needed but did show up as a failed build in the readthedocs control center.)
=> docs: fix dependencies
