.travis.yml, index.rst, tutorial_developer_workflows.rst
Add a section on developer workflows.
=> Add section/developer workflows

index.rst, tutorial_stacks.rst
=> add section on stacks after environments

index.rst, tutorial_spack_scripting.rst
Add a short section on using the `spack python` command and the `spack-python` executable.
=> Add section/spack python scripting

tutorial_spack_scripting.rst
=> Use uninstall -ay with no argument to uninstall everything

tutorial_environments.rst
=> environments: add usage and build sections

tutorial_basics.rst
Update Spack version on git checkout
=> Update Spack version on git checkout

tutorial_basics.rst
=> Basic Installation: updated output to Ubuntu 18.04

tutorial_modules.rst
=> Module Files: updated output to Ubuntu 18.04 

tutorial_developer_workflows.rst
fixes #13 
fixes #18
depends on https://github.com/spack/spack/pull/13734
=> Developer workflow: switched package from HDF5 to HWLOC

tutorial_configuration.rst
=> Configuration: updated output to Ubuntu 18.04

tutorial_packaging.rst
=> Package Creation: updated output to Ubuntu 18.04

tutorial_configuration.rst
Pretty minor formatting and grammar changes.
=> Last minute updates to Configuration Tutorial

tutorial_developer_workflows.rst
Not sure if this needs to be a `-aR` uninstall or not.
=> Add missing uninstall command to Developer Workflows Tutorial

tutorial_configuration.rst
Refers to https://github.com/spack/spack/issues/14886 
The names were not updated when merging https://github.com/spack/spack/issues/14372
=> Fixed names of attributes to modify the environment

tutorial_basics.rst
Added minor spelling fixes in `tutorial_basics.rst`. Thanks!
=> typo fixes

outputs/Makefile, outputs/defs.sh, outputs/dev.sh, outputs/dev/dev-build-1.out, outputs/dev/dev-build-2.out, outputs/dev/edit-1.out, outputs/dev/hand-build-1.out, outputs/dev/hand-build-2.out, outputs/dev/info.out, outputs/dev/setup-hwloc.out, outputs/dev/up-to-date.out, tutorial_developer_workflows.rst
=> Update and automate dev workflow section

outputs/Makefile, outputs/basics.sh, outputs/package-py-files/0.package.py, outputs/package-py-files/1.package.py, outputs/package-py-files/2.package.py, outputs/package-py-files/3.package.py, outputs/package-py-files/4.package.py, outputs/packaging.sh, outputs/packaging/build-env-configure.out, outputs/packaging/build-output.out, outputs/packaging/cleanup.out, outputs/packaging/create.out, outputs/packaging/info-mpileaks.out, outputs/packaging/install-mpileaks-1.out, outputs/packaging/install-mpileaks-2.out, outputs/packaging/install-mpileaks-3.out, outputs/packaging/install-mpileaks-4.out, outputs/packaging/repo-add.out, tutorial_packaging.rst
This is WIP for automating the packaging section
=> Automate packaging

outputs/packaging.sh, outputs/packaging/install-mpileaks-2.out, tutorial_packaging.rst
Minor bugfix for packaging output.
=> bugfix: include spack-build-out.txt

outputs/basics/checkout.out, outputs/basics/clone.out, outputs/basics/find-d-trilinos.out, outputs/basics/hdf5-hl-mpi.out, outputs/basics/install-gcc-8.3.0.out, outputs/basics/mirror.out, outputs/basics/trilinos-hdf5.out, outputs/basics/trilinos.out, outputs/basics/uninstall-ambiguous.out
Update outputs with changes from @becker33 on #50.
=> outputs: update basics

index.rst
index.rst updated with links to YouTube videos from the 2-day AWS tutorials
=> Added AWS video links

tutorial_modules.rst
This ensures later sections run smoothly.
=> remove compiler after modules section

tutorial_configuration.rst
Did a quick dry run. These are the only minor problems I found. Also added links to other configuration-related stuff.
=> Add additional changes to Config Tutorial

outputs/scripting/spack-python-1.out, outputs/scripting/spack-python-abstract.out, outputs/scripting/spack-python-concrete.out, outputs/scripting/spack-python-db-query-exclude.out, outputs/scripting/spack-python-db-query-help.out, outputs/scripting/spack-python-sans-intermediate.out, tutorial_spack_scripting.rst
I've made some significant changes to the flow of 'Scripting with Spack' in line with changes for my other section *and* the feedback I received on my first dry run of this section.
=> sc20 Revisions to scripting with spack

tutorial_developer_workflows.rst
=> remove vestigial setup step

outputs/init_spack.sh
All other references will be changed by other active PRs
=> update init_spack.sh to remove direct references to mirror path

tutorial_packaging.rst
Looks like I was off a couple of lines in the highlighting of one of the outputs.  
I also did not unindent quite far enough for one list bullet.
Finally, I simplified and refined more of the wording.
=> More package creation fixes and refinement

outputs/scripting/find-exclude-1.out, outputs/scripting/find-exclude-3.out, outputs/scripting/find-format.out, outputs/scripting/find-json.out, outputs/scripting/setup.out, outputs/scripting/spack-python-1.out
Updated outputs for newer spack version
=> ecp21: update scripting outputs

tutorial_packaging.rst
I thought I fixed the URL one before but guess I missed it.
The second is a missing space. 😦
=> Fix two 'bugs' in package creation

outputs/basics.sh, outputs/dev.sh, outputs/dev/dev-build-1.out, outputs/dev/dev-build-2.out, outputs/dev/develop-1.out, outputs/dev/develop-2.out, outputs/dev/develop-3.out, outputs/dev/develop-4.out, outputs/dev/develop-5.out, outputs/dev/develop-conc.out, outputs/dev/edit-1.out, outputs/dev/otherdevel.out, outputs/dev/setup-scr.out, outputs/dev/up-to-date.out, outputs/dev/wrapup.out, tutorial_developer_workflows.rst
script to generate output has been tested but needs to be rerun.
=> Reworked the spack develop stuff for the tutorial.

outputs/environments/env-status-2.out
@becker33 @tgamblin @tldahlgren typo in tutorial in despactivate command
=> typo in despactivate command with copy paste

tutorial_developer_workflows.rst
=> Typos found reading.

index.rst
Fixes error in https://github.com/spack/spack-tutorial/pull/122
=> Update ECP tutorial video iframe html

outputs/basics/install-gcc-8.3.0.out, outputs/basics/tcl-zlib-clang.out, outputs/basics/trilinos-hdf5.out, outputs/basics/uninstall-r-needed.out, outputs/basics/uninstall-specific.out, outputs/basics/uninstall-zlib.out, outputs/basics/zlib-O3.out, tutorial_basics.rst
This fixes a few typos and makes things more consistent.
=> Update basic installation tutorial

tutorial_advanced_packaging.rst
Fixes #125 
The tutorial is out-of-date with the changes that split `setup_environment` and `setup_dependent_environment` into separate methods for the build- and run-time environments.
TODO
=> [WIP] Advanced packaging: Update build and run environment modifications

outputs/environments/find-env-abstract-1.out, tutorial_environments.rst
This PR corrects grammar; elaborates on parts (especially to address questions raised in the ISC presentation); and adds more links (based on Todd's prior PR feedback as well as looking at additional relevant Spack reference and tutorial docs).
=> environments: ISC-inspired corrections and updates

outputs/environments/add-anonymous-1.out, outputs/environments/find-env-abstract-1.out, outputs/environments/find-env-concrete-1.out, tutorial_environments.rst
This PR fixes a command error and makes the outputs consistent with what should be output at that point in the tutorial.  This is *especially* important for reproducible outputs. 😳
=> Environments: More corrections, especially to reproducible outputs

tutorial/examples/3.package.py, tutorial/examples/4.package.py, tutorial_packaging.rst
These are all very minor. No problem if this doesn't get merged before tomorrow's tutorial.
=> Packaging Tutorial: minor grammar changes

tutorial_environments.rst
Also removes an extraneous "also".
=> Remove premature concrete env activation reference

outputs/basics.sh, outputs/cache.sh, outputs/defs.sh, outputs/dev.sh, outputs/modules.sh, outputs/scripting.sh
Initial SC-related tweak for spack release and gcc 8 compiler change.
=> Updated spack version and gcc8 compiler

.github/workflows/containers.yaml, docker/Dockerfile, docker/config.yaml, docker/packages.yaml, outputs/Makefile
Modifications:
To build the image locally:
```
$ cd docker
$ docker build  -t spack/tutorial:latest .
```
=> Add a Dockerfile to build the output

outputs/scripting.sh, outputs/scripting/find-exclude-1.out, outputs/scripting/find-exclude-3.out, outputs/scripting/find-format.out, outputs/scripting/find-json.out, outputs/scripting/setup.out, outputs/scripting/spack-python-1.out, outputs/scripting/spack-python-abstract.out, outputs/scripting/spack-python-concrete.out
Uses docker container built from https://github.com/spack/spack-tutorial/pull/140
=> Updates scripting tutorial for v17

outputs/environments/add-1.out, outputs/environments/add-2.out, outputs/environments/add-3.out, outputs/environments/add-anonymous-1.out, outputs/environments/anonymous-create-1.out, outputs/environments/anonymous-create-2.out, outputs/environments/cat-config-1.out, outputs/environments/concretize-f-1.out, outputs/environments/config-get-1.out, outputs/environments/create-from-file-1.out, outputs/environments/env-create-1.out, outputs/environments/env-create-2.out, outputs/environments/env-install-1.out, outputs/environments/env-status-2.out, outputs/environments/env-swap-1.out, outputs/environments/env-uninstall-1.out, outputs/environments/find-no-env-1.out, outputs/environments/install-anonymous-1.out, outputs/environments/lockfile-1.out, outputs/environments/remove-anonymous-1.out, outputs/environments/show-paths-1.out, outputs/environments/spec-1.out, outputs/environments/spec-2.out, outputs/environments/use-mpi-1.out, tutorial_environments.rst
Using the Docker image build with #155 and the scripts in the `output` directive. Might need some manual refinement.
=> ISC22: updated environment section

outputs/config/0.compiler_flags.out, outputs/config/0.externals.out, outputs/config/0.prefs.out, outputs/config/1.externals.out, outputs/config/1.prefs.out, outputs/config/2.externals.out, outputs/config/3.externals.out, outputs/config/3.prefs.out, tutorial_configuration.rst
- Drop the `packages:variants:all:~shared` bit, it's not picked up, somehow
=> config: fixes for 0.18

outputs/basics.sh, outputs/basics/tcl-zlib-clang.out, outputs/basics/zlib-O3.out, tutorial_basics.rst
Some small things I missed in the last PR.
=> basics: Fix a few inconsistencies

requirements.txt, tutorial_configuration.rst
Also move cleanup actions into their own section at the end.
=> Discuss package requirements config in tutorial

common/setup.rst
This works around issues with repo cache
=> Clone the release branch directly

.gitmodules
=> bump version _spack_root to v0.19.1

outputs/stacks.sh, outputs/stacks/concretize-0.out, outputs/stacks/concretize-1.out, outputs/stacks/concretize-2.out, outputs/stacks/concretize-3.out, outputs/stacks/modules-0.out, outputs/stacks/modules-2.out, outputs/stacks/modules-3.out, outputs/stacks/modules-5.out, outputs/stacks/view-0.out, tutorial_stacks.rst
=> stacks: update output

outputs/basics.sh, outputs/defs.sh, outputs/init_spack.sh
- Make it dash compatible (except for pipefail)
- quiet please
=> Small fixes

docker/Dockerfile
Reverts spack/spack-tutorial#212
=> Revert "Update Dockerfile to use v0.19.1"

common/setup.rst
This makes following each section separately a bit better
=> Improve setting up procedure

outputs/environments.sh, outputs/environments/add-anonymous-1.out, outputs/environments/cat-config-1.out, outputs/environments/env-fail-install-1.out, outputs/environments/env-install-1.out, outputs/environments/env-list-3.out, outputs/environments/myproject-zlib-1.out, outputs/environments/remove-anonymous-1.out, outputs/environments/show-mpicc-1.out, tutorial_environments.rst
Adjusted some commands and outputs to be more accurate.
=> Environments: Fix commands and outputs

docker/Dockerfile, docker/concretizer.yaml, docker/packages.yaml, outputs/basics.sh, outputs/defs.sh, outputs/environments.sh, outputs/init_spack.sh
=> Update the container to ubuntu:22.04

common/setup.rst
Will there be a tag for the container? I just updated it to `latest`.
=> Update setup for ISC

common/setup.rst, outputs/Makefile, outputs/defs.sh
- store digest for now
- bump spack
=> minimal fixes

outputs/defs.sh, outputs/modules.sh, outputs/scripting.sh, outputs/stacks.sh, outputs/stacks/examples/0.spack.stack.yaml, outputs/stacks/examples/5.spack.stack.yaml, outputs/stacks/examples/6.spack.stack.yaml, outputs/stacks/examples/7.spack.stack.yaml, tutorial_basics.rst, tutorial_configuration.rst, tutorial_modules.rst, tutorial_stacks.rst
- use backports branch
- toolchain changes
=> more fixes

outputs/stacks/examples/1.spack.stack.yaml, outputs/stacks/examples/2.spack.stack.yaml, outputs/stacks/examples/3.spack.stack.yaml, outputs/stacks/examples/4.spack.stack.yaml, outputs/stacks/examples/5.spack.stack.yaml, outputs/stacks/examples/6.spack.stack.yaml, outputs/stacks/examples/7.spack.stack.yaml, outputs/stacks/examples/8.spack.stack.yaml, outputs/stacks/examples/9.spack.stack.yaml
=> update toolchain again

outputs/stacks.sh
Needs to be updated again after https://github.com/spack/spack/pull/40939
=> use older lmod to work around exit 1 issue

outputs/stacks.sh
=> remove adding lmod version

outputs/environments.sh
=> more setup fixes

tutorial_modules.rst
- use `true` in json, not `True`
- fix highlight issue
- fix reference to projection key
=> modules: small fixes

.github/workflows/regenerate.yaml
=> Add workflow dispatch action

outputs/cache.sh
Simplify the environment creation steps in the mirror's tutorial.
=> Simply the enviornment creation in mirrors tutorial

docker/Dockerfile
=> update build cache

tutorial_buildsystems.rst
See https://github.com/spack/spack/pull/36679
=> Change default CMake build type from RelWithDebInfo to Release

outputs/Makefile
The new image contains the modifications in https://github.com/spack/spack/pull/44073
=> Update docker image sha256

tutorial_binary_cache.rst
=> binary cache: update

outputs/environments.sh, outputs/environments/env-create-2.out, outputs/environments/env-install-1.out, outputs/environments/env-remove-1.out, outputs/environments/incremental-1.out, outputs/environments/incremental-2.out, outputs/environments/install-independent-1.out, outputs/environments/lockfile-1.out, outputs/environments/use-mpi-1.out, tutorial_environments.rst
=> fix environments section

outputs/scripting.sh, outputs/scripting/spack-python-abstract.out, outputs/scripting/spack-python-concrete.out, outputs/scripting/spack-python-db-query-exclude.out, outputs/scripting/spack-python-db-query-help.out, outputs/scripting/spack-python-sans-intermediate.out, tutorial_spack_scripting.rst
Updating scripting section -- some autogenerated, some manual
=> update scripting section outputs

outputs/basics.sh, outputs/defs.sh, tutorial_basics.rst
1. update version of spack checked out
2. update hash for optimized zlib-ng
3. change `--depth=100` to `--depth=2` for speed
=> updates for the basics section for v0.23 / sc24

index.rst, tutorial_environments.rst
This is very much a subjective PR. I'm editing the section for how I'd like to give it on Friday, but I'm open to getting feedback on sections I'm modified if others dislike my edits.
=> Environments tutorial: improve flow and content

outputs/basics/clone.out, outputs/basics/gmake.out, outputs/basics/hdf5-hl-mpi.out, outputs/basics/hdf5-no-mpi.out, outputs/basics/hdf5.out, outputs/basics/install-gcc-12.1.0.out, outputs/basics/mirror.out, outputs/basics/repo.out, outputs/basics/tcl-zlib-clang.out, outputs/basics/tcl-zlib-hash.out, outputs/basics/tcl.out, outputs/basics/trilinos-hdf5.out, outputs/basics/trilinos.out, outputs/basics/zlib-2.0.7.out, outputs/basics/zlib-O3.out, outputs/basics/zlib-clang.out, outputs/basics/zlib-gcc-10.out, outputs/config/0.compiler_flags.out, outputs/environments.sh, outputs/environments/config-get-1.out, outputs/environments/env-create-2.out, outputs/environments/env-install-1.out, outputs/environments/incremental-1.out, outputs/environments/incremental-2.out, outputs/environments/install-independent-1.out, outputs/environments/use-mpi-1.out, tutorial_configuration.rst, tutorial_environments.rst
Final minor fixes from testing on both potential AMIs
=> 1.0/last updates tuesday sections

.gitignore, conf.py
Avoid that common/setup.html is generated
=> conf.py: exclude common/*
